### ISSUE TITLE
Improve Compatibility with RequireJS

### ISSUE THREAD

**Issue by Joeao** [y-js/y-websockets-client#1]
The requiring of utf8 @:3252 and json3 @:6500 imports empty objects when using RequireJS. Both plugins [suggest](https://github.com/bestiejs/json3#asynchronous-module-loaders) being required the standard way for RequireJS, e.g. by setting their path first, rather than using `require("json3")`.
If the user requires these plugins themselves, they will be overwritten by yjs-websockets-client.

**Comment by dmonad** [comment]
fixed with release 0.7.10
